apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: todoquery
spec:
  type: bindings.azure.cosmosdb
  initTimeout: 30s
  version: v1
  metadata:
  - name: url
    value: "https://walcron-db.documents.azure.com:443/"
  - name: database
    value: "TodoDatabase"
  - name: collection
    value: "Todos"
  - name: authMode
    value: "managed"
